## Lista Exercícios 3

In [2]:
import numpy as np

## Exercício 1

Matriz Identidade

Seja M uma matriz quadrada de ordem n. A matriz M é chamada de Matriz Identidade de ordem n (indicada por In) quando os elementos da diagonal principal são todos iguais a 1 e os elementos restantes são iguais a zero.

**Desenvolva** uma função que retorne a matriz identidade de dimensão n.

Exemplo de matriz identidade de dimensão 3x3:
```
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])
```

Exemplo de matriz identidade de dimensão 5x5:
```
array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])
```    


In [4]:
num_quadrado = 5
itens = num_quadrado ** 2
vetor = np.zeros(itens).reshape((num_quadrado, num_quadrado))

for i in range(0, num_quadrado):
    vetor[i][i] = 1

print(vetor)
print()
arr = np.zeros((5,5))
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Exercício 2

Considere os arrays a e b, descubra os índices dos elementos com o mesmo valor.

In [77]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

a.sort()
b.sort()

In [78]:
vectorA = np.array([])

for i in range(1,10):
    if(a[i] == a[i-1]):
        vectorA = np.append(vectorA,i)
        
print(vectorA)

[2. 4. 5. 7.]


In [79]:
vectorB = np.array([])

for i in range(1,10):
    if(b[i] == b[i-1]):
        vectorB = np.append(vectorB,i)
        
print(vectorB)

[1. 3. 5. 8.]


In [6]:
a1 = np.array([1,2,3,2,3,4,3,4,5,6])
b1 = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a1 == b1)

(array([1, 3, 5, 7], dtype=int64),)

## Exercício 3

Crie um array de 2 dimensões (5 X 3) contendo números aleatórios decimais entre 5 e 10.

In [33]:
vetor2 = np.random.randint(5,10, [5,3])
vetor2

array([[8, 5, 7],
       [9, 7, 7],
       [7, 7, 6],
       [5, 5, 9],
       [8, 9, 7]])

## Exercício 4

Dado o array a, efetue a divisão do menor valor pelo maior valor de cada linha.

In [30]:
np.random.seed(100)
vetor3 = np.random.randint(1,10, [5,4])
vetor3

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5],
       [1, 7, 3, 5]])

In [52]:
for i in range(0,5):
    print(str(i),":",max(vetor3[i]) / min(vetor3[i]))

0 : 2.25
1 : 8.0
2 : 2.0
3 : 9.0
4 : 7.0


## Exercício 5

Elimine os NAN do array a.

In [34]:
vetor4 = np.array([[1, np.nan, 3], [np.nan, 5, 6], [7, 8, np.nan]])
vetor4

array([[ 1., nan,  3.],
       [nan,  5.,  6.],
       [ 7.,  8., nan]])

In [41]:
#~ = not (ou seja, not isnan)
vetor5 = vetor4[~np.isnan(vetor4)]
vetor5

array([1., 3., 5., 6., 7., 8.])

## Exercício 6

Dado o array a de 2 dimensões e o array b de uma dimensão apenas. Subtraia o array b do array a, de forma que cada elemento do array b subtraia a __linha__ correspondente do array a.

In [7]:
vetor6 = np.array([[3,3,3],[4,4,4],[5,5,5]])
vetor6

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [8]:
vetor7 = np.array([1,2,3])
vetor7

array([1, 2, 3])

In [9]:
vetor8 = vetor6 - vetor7
vetor8

array([[2, 1, 0],
       [3, 2, 1],
       [4, 3, 2]])

In [11]:
vetor6 = np.array([[3,3,3],[4,4,4],[5,5,5]])
vetor6

vetor7 = np.array([1,2,3])
vetor7

vetor6 - vetor7.reshape(-1,1)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])