## Exercício 2

In [1]:
import numpy as np

## 1 - Crie um vetor com 10 elementos 0.

In [3]:
vetor1 = np.zeros(10)
vetor1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

## 2 - Crie um vetor com 10 elementos 0 e inicialize o quinto elemento com o valor 1.

In [4]:
vetor2 = np.zeros(10)
vetor2[4] = 1
vetor2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

```
array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])
```

## 3 - Crie um vetor com valores em sequencia de 10 à 49.

In [12]:
vetor3 = np.arange(start=1, stop=10, step=3)
vetor3
vetor3 = np.arange(start=10, stop=50)
vetor3
vetor3 = np.arange(10,50)
vetor3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])
```

## 4 - Crie um vetor com valores inteiros de 50 à 0.

In [15]:
#de 50 à zero somando -1
vetor4 = np.arange(50,-1,-1)
vetor4

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

```
array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])
```


## 5 - Crie um vetor com valores inteiros de 0 à 49 em seguida inverta a ordem do vetor.

In [16]:
vetor5 = np.arange(0,50)
vetor5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [17]:
vetor5[::-1].sort()
vetor5

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])
       
array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])
```

## 6 - Crie uma matriz 3 x 3 com valores de 1 à 9.

In [19]:
vetor6 = np.arange(1,10).reshape((3, 3))
vetor6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

```
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
```

## 7 - Dada o vetor [1, 3, 0, 3, 0, 3, 2, 0, 1, 0], descubra os índices dos elementos diferentes de zero.

In [32]:
vetor7 = np.array([1,3,0,3,0,3,2,0,1,0])
np.where(vetor7 != 0)[0]

array([0, 1, 3, 5, 6, 8], dtype=int64)

```
array([0, 1, 3, 5, 6, 8], dtype=int64)
```

## 8 - Crie uma matriz 3 x 3 x 3 com números aleatórios.

In [33]:
vetor8 = np.random.randn(3, 3, 3)
vetor8

array([[[ 1.94351775, -1.75042611, -1.26974709],
        [-0.23002646,  0.84593428, -0.3981446 ],
        [-0.72429099,  0.07647011,  0.44111861]],

       [[ 1.33390036, -0.00410905, -1.45502098],
        [ 2.58586323, -0.46111636, -1.29329503],
        [ 1.04718046, -0.89419456,  0.64538735]],

       [[ 1.0120891 , -0.96581118,  0.20208717],
        [-0.81531717, -1.27265113, -1.98607484],
        [ 0.63350279, -1.33930778,  0.13602936]]])

Exemplo:
```
array([[[0.61286554, 0.74921735, 0.61223858],
        [0.96047489, 0.65628431, 0.79342544],
        [0.70941175, 0.98583943, 0.00318382]],

       [[0.85867772, 0.93941609, 0.30006033],
        [0.79160418, 0.0865738 , 0.69892442],
        [0.33265707, 0.25932833, 0.11447914]],

       [[0.24026643, 0.23737787, 0.04470459],
        [0.11646793, 0.32991814, 0.85027852],
        [0.25262905, 0.1805445 , 0.40050341]]])
```

## 9 - Crie um vetor de tamanho 10 com números aleatórios em ordenados em ordem crescente.

In [34]:
vetor9 = np.random.randn(10)
vetor9

array([-0.22140001,  1.41464832,  2.54860616, -0.15499278,  0.96214763,
        0.22824709, -1.06355429,  0.596002  ,  0.44757779, -1.74601758])

In [35]:
vetor9.sort()
vetor9

array([-1.74601758, -1.06355429, -0.22140001, -0.15499278,  0.22824709,
        0.44757779,  0.596002  ,  0.96214763,  1.41464832,  2.54860616])

Exemplo:
```
array([0.56239709, 0.36663249, 0.24432617, 0.43788321, 0.89709646,
       0.58901959, 0.26398762, 0.82502151, 0.3666227 , 0.47548132])
       
array([0.24432617, 0.26398762, 0.3666227 , 0.36663249, 0.43788321,
       0.47548132, 0.56239709, 0.58901959, 0.82502151, 0.89709646])
```